f=open("test","w")
content=f.write("the life is short , you need python")
print(content)
f.close()
f=open("test","r")
content=f.read(5)
print(content)
content=f.read()
print(content)
f.close()
f=open("test","a")
content=f.write("python is easy")
print(content)
f.close()
